- WebAPI/WebAPI/Controllers/ProductsController.cs
- WebAPI/WebAPI/Data/DataContext.cs
- WebAPI/WebAPI/Helpers/Services/ProductService.cs
- WebAPI/WebAPI/Models/Dtos/ProductDto.cs
- WebAPI/WebAPI/Models/Entities/ProductEntity.cs
- WebAPI/WebAPI/Models/Schemas/ProductSchema.cs
- WebAPI/WebAPI/Program.cs
- WebAPI/WebAPI/WebAPI.csproj
- WebAPI/WebAPI/appsettings.json
Added all product related files to demonstrate file structure. Installed all nuget packages.
> Initial api setup

- WebAPI/WebAPI.sln
- WebAPI/WebAPITest/GlobalUsings.cs
- WebAPI/WebAPITest/ProductServiceTest.cs
- WebAPI/WebAPITest/WebAPITest.csproj
Created test project and ProductService.GetAllAsync() test.
> Story 74 be/test

- WebAPI/WebAPI/Controllers/CategoryController.cs
- WebAPI/WebAPI/Controllers/ProductsController.cs
- WebAPI/WebAPI/Helpers/Services/CategoryService.cs
- WebAPI/WebAPI/Models/Dtos/CategoryDto.cs
- WebAPI/WebAPI/Models/Entities/CategoryEntity.cs
- WebAPI/WebAPI/Program.cs
- WebAPI/WebAPITest/CategoryServiceTests.cs
- WebAPI/WebAPITest/ProductServiceTest.cs
- WebAPI/WebAPITest/ProductServiceTests.cs
Created, dto, service and controller for categories. Added a unit test for the GetAllAsync method in the category service.
> Story 41 be/view categories

- WebAPI/WebAPI/Controllers/ProductsController.cs
- WebAPI/WebAPI/Helpers/Repositories/CategoryRepo.cs
- WebAPI/WebAPI/Helpers/Repositories/GenericRepo.cs
- WebAPI/WebAPI/Helpers/Repositories/ProductRepo.cs
- WebAPI/WebAPI/Helpers/Services/CategoryService.cs
- WebAPI/WebAPI/Helpers/Services/ProductService.cs
- WebAPI/WebAPI/Program.cs
- WebAPI/WebAPITest/CategoryServiceTests.cs
- WebAPI/WebAPITest/DatabaseFixture.cs
- WebAPI/WebAPITest/ProductServiceTests.cs
Updated test to use fixture instead of separate databases. Created service method and controller endpoint to allow getting products by category.
> Story 32 be/sort by categories

- WebAPI/WebAPI/Controllers/TagsController.cs
- WebAPI/WebAPI/Helpers/Repositories/TagRepo.cs
- WebAPI/WebAPI/Helpers/Services/TagService.cs
- WebAPI/WebAPI/Models/Dtos/TagDto.cs
- WebAPI/WebAPI/Models/Entities/TagEntity.cs
- WebAPI/WebAPI/Program.cs
Added tag controller, DTO, repo and service
> Story 41 be/view categories tag controller

- manero-frontend/src/components/Layout/ContactBurgerMenu.jsx
- manero-frontend/src/components/Layout/Navbar.jsx
- manero-frontend/src/scss/components/_contact-sidebar.scss
- manero-frontend/src/scss/components/_nav.scss
- manero-frontend/src/scss/core/_variables.scss
update to the contact sidebar.
> Scrum-39-fe/contact-sidebar

- WebAPI/WebAPI/Controllers/OrdersController.cs
- WebAPI/WebAPI/Controllers/ProductsController.cs
- WebAPI/WebAPI/Controllers/TagsController.cs
- WebAPI/WebAPI/Helpers/Repositories/ProductRepo.cs
- WebAPI/WebAPI/Helpers/Seeders/Seeder.cs
- WebAPI/WebAPI/Helpers/Services/CategoryService.cs
- WebAPI/WebAPI/Helpers/Services/OrderService.cs
- WebAPI/WebAPI/Models/Dtos/AddressDto.cs
- WebAPI/WebAPI/Models/Dtos/CategoryDto.cs
- WebAPI/WebAPI/Models/Dtos/OrderDto.cs
- WebAPI/WebAPI/Models/Dtos/OrderItemDto.cs
- WebAPI/WebAPI/Models/Dtos/ProductDto.cs
- WebAPI/WebAPI/Models/Entities/CategoryEntity.cs
- WebAPI/WebAPI/Models/Entities/OrderItemEntity.cs
- WebAPI/WebAPI/Models/Entities/SizeEntity.cs
- WebAPI/WebAPI/Models/Entities/StatusEntity.cs
- WebAPI/WebAPITest/Helpers/DatabaseFixture.cs
- WebAPI/WebAPITest/Helpers/SeederTestDatabase.cs
- WebAPI/WebAPITest/ServiceTests/AddressServiceTests.cs
- WebAPI/WebAPITest/ServiceTests/CategoryServiceTests.cs
- WebAPI/WebAPITest/ServiceTests/CustomerServiceTest.cs
- WebAPI/WebAPITest/ServiceTests/OrderServiceTests.cs
- WebAPI/WebAPITest/ServiceTests/ProductServiceTests.cs
Refactored, reformatted and commented entire backend.
> Scrum 123 be/refactor

- manero-frontend/src/components/CartProductCard.jsx
- manero-frontend/src/components/DiscountCard.jsx
- manero-frontend/src/components/Layout/LayoutDesktop.jsx
- manero-frontend/src/helpers/add-to-cart.js
- manero-frontend/src/pages/Cart.jsx
- manero-frontend/src/pages/ProductDetails.jsx
- manero-frontend/src/scss/components/_button.scss
- manero-frontend/src/scss/core/_base.scss
- manero-frontend/src/scss/pages/_cart.scss
Fixed some warnings/issues and (hopefully) got the handleAddToCart and handleRemoveFromCart to work.
I'll just leave this here for Monday!
> Story 45/cart fixes

- WebAPI/WebAPITest/UnitTests/ServiceTests/AddressService_Unit.cs
- WebAPI/WebAPITest/UnitTests/ServiceTests/Category_Unit.cs
- WebAPI/WebAPITest/UnitTests/ServiceTests/CustomerService_Unit.cs
- WebAPI/WebAPITest/UnitTests/ServiceTests/OrderService_Unit.cs
- WebAPI/WebAPITest/UnitTests/ServiceTests/ProductService_Unit.cs
> Test backend overhaul

- WebAPI/WebAPI/Controllers/ProductsController.cs
- WebAPI/WebAPI/Helpers/Services/ProductService.cs
- WebAPI/WebAPI/Interface/Services/IProductService.cs
- WebAPI/WebAPITest/UnitTests/ServiceTests/ProductService_Unit.cs
Co-authored-by: Simon <simon-off@users.noreply.github.com>
> Add test for productService.GetById

- manero-frontend/src/components/CheckoutItem.jsx
- manero-frontend/src/pages/Cart.jsx
- manero-frontend/src/pages/Checkout.jsx
- manero-frontend/src/routes.jsx
- manero-frontend/src/scss/main.scss
- manero-frontend/src/scss/pages/_checkout.scss
Added checkout page where you can see all of your items that you have picked.
Co-authored-by: Jimmieost <Jimmieost@users.noreply.github.com>
> Add checkout page view

- manero-frontend/src/pages/Products.jsx
- manero-frontend/src/scss/pages/_products.scss
Co-authored-by: Viggo Valfridsson <ViggoValfridsson@users.noreply.github.com>
> Add user feedback when entering unmatched paramet

- manero-frontend/src/components/Layout/ContactBurgerMenu.jsx
- manero-frontend/src/pages/Checkout.jsx
- manero-frontend/src/scss/components/_contact-sidebar.scss
- manero-frontend/src/scss/pages/_checkout.scss
Fixed few bugs and unitended styling in home and sidebar component
> Scrum-140-fe/bugfix-home/contact

- manero-frontend/src/components/DiscountCard.jsx
- manero-frontend/src/components/ProductGridCard.jsx
- manero-frontend/src/components/ProductListCard.jsx
- manero-frontend/src/pages/Home.jsx
> Scrum 140 fe/home fixes

- manero-frontend/src/scss/components/_discount-card.scss
- manero-frontend/src/scss/components/_product-grid.scss
- manero-frontend/src/scss/components/_product-list.scss
- manero-frontend/src/scss/pages/_home.scss
fixed a few padding bugs on home page
> add further styling on homepage

- WebAPI/WebAPI/Controllers/OrdersController.cs
- WebAPI/WebAPI/Helpers/Repositories/GenericRepo.cs
- WebAPI/WebAPI/Helpers/Services/OrderService.cs
- WebAPI/WebAPI/Interface/Repositories/IRepo.cs
- WebAPI/WebAPI/Interface/Services/IOrderService.cs
Added AnyAsync() method to repos. Created better logic for checking if product items are valid.
> Order controller refactor

- manero-frontend/src/components/PaymentCard.jsx
- manero-frontend/src/pages/AddPaymentCard.jsx
Updated the creditcard component so it updates the name and number dynamically when you type.
> Add dynamic values to name and number paymentcard

- WebAPI/WebAPI/Controllers/AccountController.cs
- WebAPI/WebAPI/Helpers/Services/AccountService.cs
- WebAPI/WebAPI/Interface/Services/IAccountService.cs
- WebAPI/WebAPI/Models/Schemas/SignInSchema.cs
- WebAPI/WebAPI/Program.cs
Sign in endpoint that returns JWS token
> Story 20 be/sign in

- manero-frontend/src/App.jsx
- manero-frontend/src/components/ProductGridCard.jsx
- manero-frontend/src/components/ProductListCard.jsx
- manero-frontend/src/hooks/useWishlist.jsx
- manero-frontend/src/models/WishlistItem.js
- manero-frontend/src/pages/Home.jsx
- manero-frontend/src/pages/WishList.jsx
- manero-frontend/src/routes.jsx
- manero-frontend/src/scss/main.scss
- manero-frontend/src/scss/pages/_wishlist.scss
Create wishlist page with functionality to add and remove products to wishlist.
> Scrum-57-fe/wishlist-page

- WebAPI/WebAPI/Controllers/AccountController.cs
- WebAPI/WebAPI/Helpers/Services/AccountService.cs
- WebAPI/WebAPI/Interface/Services/IAccountService.cs
- WebAPI/WebAPI/Models/Dtos/UserDto.cs
- WebAPI/WebAPI/Models/Identity/AppUser.cs
- WebAPI/WebAPI/WebAPI.csproj
Added account page with authentication and authorization
> Scrum 27 be/account page

- WebAPI/WebAPI/Controllers/AccountController.cs
- WebAPI/WebAPI/Helpers/Services/AccountService.cs
- WebAPI/WebAPI/Interface/Services/IAccountService.cs
- WebAPI/WebAPI/Models/Schemas/SignUpSchema.cs
- WebAPI/WebAPI/Models/Schemas/UserUpdateSchema.cs
Add update functionality to API
> Scrum 28 be/update account

- manero-frontend/src/pages/Products.jsx
Co-authored-by: Simon <simon-off@users.noreply.github.com>
> Add frontend functionality for order by price

- WebAPI/WebAPI/Helpers/Services/OrderService.cs
- WebAPI/WebAPI/Migrations/20231101100702_AddOrderComment.Designer.cs
- WebAPI/WebAPI/Migrations/20231101100702_AddOrderComment.cs
- WebAPI/WebAPI/Models/Dtos/OrderDto.cs
- WebAPI/WebAPI/Models/Entities/OrderEntity.cs
- WebAPI/WebAPI/Models/Schemas/OrderCustomerCreateSchema.cs
- WebAPI/WebAPI/Models/Schemas/OrderUserCreateSchema.cs
Add order comment functionality
> Story 55 be/order comment

- WebAPI/WebAPI/Controllers/AddressesController.cs
- WebAPI/WebAPI/Controllers/BankCardsController.cs
- WebAPI/WebAPI/Data/DataContext.cs
- WebAPI/WebAPI/Helpers/Repositories/BankCardRepo.cs
- WebAPI/WebAPI/Helpers/Services/AccountService.cs
- WebAPI/WebAPI/Helpers/Services/BankCardService.cs
- WebAPI/WebAPI/Interface/Repositories/IBankCardRepo.cs
- WebAPI/WebAPI/Interface/Services/IAccountService.cs
- WebAPI/WebAPI/Interface/Services/IBankCardService.cs
- WebAPI/WebAPI/Migrations/20231101103327_CreateBankCard.Designer.cs
- WebAPI/WebAPI/Migrations/20231101103327_CreateBankCard.cs
- WebAPI/WebAPI/Migrations/20231101103658_AddExpirationDate.Designer.cs
- WebAPI/WebAPI/Migrations/20231101103658_AddExpirationDate.cs
- WebAPI/WebAPI/Migrations/20231101105216_AddUserToCard.Designer.cs
- WebAPI/WebAPI/Migrations/20231101105216_AddUserToCard.cs
- WebAPI/WebAPI/Migrations/20231101123802_UpdateUserIdToBeNullable.Designer.cs
- WebAPI/WebAPI/Migrations/20231101123802_UpdateUserIdToBeNullable.cs
- WebAPI/WebAPI/Models/Dtos/BankCardDto.cs
- WebAPI/WebAPI/Models/Entities/BankCardEntity.cs
- WebAPI/WebAPI/Models/Schemas/BankCardCreateSchema.cs
- WebAPI/WebAPI/Models/Schemas/BankCardUpdateSchema.cs
- WebAPI/WebAPI/Models/ServiceStatusCodeReturn.cs
- WebAPI/WebAPI/Program.cs
Add paymen crud operations. 
Refactor token verification.
> Story 19 be/crud payment options

- WebAPI/WebAPITest/Helpers/SeederTestDatabase.cs
- WebAPI/WebAPITest/IntegrationTests/ServiceTests/ProductService_Integration.cs
Co-authored-by: Simon <simon-off@users.noreply.github.com>
> Add order by test

- frontend/src/components/ThemedInput.jsx
- frontend/src/pages/profile/SignUp.jsx
Updated signUp section so you can post your information to the backend
Co-authored-by: Viggo Valfridsson <ViggoValfridsson@users.noreply.github.com>
Co-authored-by: nabi <MohammadNabi01@users.noreply.github.com>
Co-authored-by: Leon Lagergren <Lwonla@users.noreply.github.com>
> Update signUp so it works with backend

- backend/WebAPI/Controllers/AccountController.cs
- backend/WebAPI/Models/Schemas/UpdatePasswordSchema.cs
Create backend functionality to change password when logged in.
> Create change password endpoint

- frontend/test/helpers/getCookieByName.test.js
- frontend/test/hooks/useWindowResize.test.js
> Add test for getCookiebyName and useWindowResize

- frontend/src/hooks/useCart.jsx
> Add local storage for  cart
